### ISSUE TITLE
Connection management problem for the execution of a query when several connections are declared (solved)

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#10]
When several connections are declared, even if only one of them is "connected" and is "selected", the request to execute a query ("Run all" choice in the contextual menu of the editor view) fails: "the query failed because it is not associated with a connection".

![db2de-1](https://user-images.githubusercontent.com/63861965/97613696-493a6380-1a19-11eb-851b-8cc3340ed17c.png)

![db2de-2](https://user-images.githubusercontent.com/63861965/97613713-4f304480-1a19-11eb-915a-7c9368779aca.png)

![db2de-3](https://user-images.githubusercontent.com/63861965/97614104-d1b90400-1a19-11eb-88c4-fb78cf919f7c.png)

![db2de-4](https://user-images.githubusercontent.com/63861965/97614129-d978a880-1a19-11eb-89a5-bad7197ec677.png)

[db2de-5_log.txt](https://github.com/IBM/db2forzosdeveloperextension-about/files/5460449/db2de-5_log.txt)

**Comment by FALLAI-Denis** [comment]
Fixed issue: lack of information on using the extension.

You must activate a connection from the status bar ...

![db2de-5](https://user-images.githubusercontent.com/63861965/97616604-11351f80-1a1d-11eb-85f9-2526955eb799.png)

![db2de-6](https://user-images.githubusercontent.com/63861965/97616616-14c8a680-1a1d-11eb-961f-91977974b925.png)

![db2de-7](https://user-images.githubusercontent.com/63861965/97616637-185c2d80-1a1d-11eb-846d-323758ae611f.png)

![db2de-8](https://user-images.githubusercontent.com/63861965/97616657-1d20e180-1a1d-11eb-93f4-cd39ee6ff6cf.png)

![db2de-9](https://user-images.githubusercontent.com/63861965/97616681-25791c80-1a1d-11eb-8437-4e4b294f6c19.png)

**Comment by realkendrickren** [comment]
@FALLAI-Denis thanks, you figured out so quickly! That is correct that one connection needs to be chosen and associated with a file when there are multiple connections defined. 
As mentioned in another issue (#9 ), we are planning to add more intelligence to this area in future to make things easier.

**Comment by FALLAI-Denis** [comment]
I suggest adding a "run all with connection... » choice to select/change the crurent connection. 

When no connection is selected, the "run all" choice should be unavailable (hidden or disabled).

**Comment by FALLAI-Denis** [comment]
In our context of use, the current schema special register is dependent on the Db2 system. 
Is it normal that the current schema is an attribute of the query in the "config.json" file?

Perhaps it would be necessary to separate the attributes which are linked to the sql code of the query, (terminator), and those which are linked to the execution context (connection, current schema), and therefore manage two types of objects in the "config.json" file: "query" and "context".

In this case the menus should be "run all | selected with context ..." and open a popup to sélect the context selection

**Comment by realkendrickren** [comment]
@FALLAI-Denis thanks for bringing up the scenario, this is one of items we plan to support in future -- to allow some of special registers at connection level. I'll mark this as enhancement.

**Comment by realkendrickren** [comment]
@FALLAI-Denis we today delivered a new version 0.5.5 which has full support on JDBC properties and JDBC tracing. The new version allows you to define the properties like currentSchema, currentSQLID, and so on at the connection level now. We also enhanced the logic on assigning the connection to the SQL file. Please upgrade the extension and give a try.
