### ISSUE TITLE
End of support Spring Boot 2.X

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#103]
Hi,

we noticed that the Tuning Services use Spring Boot version 2.6.10. This version is out of support since 24 Nov 2022 except commercial support is used.

Is the Spring Boot Version that Tuning Services use covered by commercial support?

If not we need an update to a supported version as soon as possible. Even Spring Boot 2.7.X will be out of OSS support on 18 Nov 2023. If you want to upgrade to 3.X Java 17 is required but Java 17 is not available vor z/OS yet so you can get into trouble here as well.

Kind regards
Martin

**Comment by amadhavia** [comment]
Hi Martin, 

Thank you for bringing this to our attention. We will look into this and let you know our next steps for the Spring Boot 2.x library. 

Regards, 
Madhavi Amirneni

**Comment by zhaoxq** [comment]
@Marty850  Thanks for bringing the question.
My understanding on "End of Support" is that we cannot get any support if there is an issue.  But we can still get security patch if there is CVE.
If this concerns you, we just released a new PTF which uses Spring Boot 2.7.5.

**Comment by Marty850** [comment]
I thought "End of Support" also means "end of security patches" and so tuning services would be a potential security risk.  

Can you tell me the PTF number for ne new PTF? I could not find it.

Thank you very much

**Comment by zhaoxq** [comment]
It's UI92499.

My understanding is that "End of life" means no security patch, correct me if I'm wrong.

**Comment by Marty850** [comment]
I think you are right! I found the following statement:

> Spring Boot releases are usually marked end of life 27 months after they were released.
> 
> Please note that a version can be out of support before it is end of life. During this time you should only expect releases for critical bugs or security issues.

(Source: https://github.com/spring-projects/spring-boot/wiki/Supported-Versions)

So EOL should be at 19.08.2024 for version 2.7. Unfortunately they don't have a column for EOL in their officiel support table (https://spring.io/projects/spring-boot#support).

I hope that is enought time for IBM to get JAVA 17 running on z/OS ;-) Do you know something about release plans for Java 17 on z/OS?

Thank you very much

**Comment by zhaoxq** [comment]
Not sure if you have access to this page, but I don't see a date on it.
https://www.ibm.com/docs/en/announcements/statement-direction-semeru-version-17?region=US

**Comment by Marty850** [comment]
Thanks, I have access to the page. Sounds like waiting is the only thing we can do ;-)

**Comment by equalchenbj** [comment]
Closing this issue as the original problem is resolved.
