### ISSUE TITLE
Getting error when trying to invoke "SQL Tuning Options"

### ISSUE THREAD

**Issue by ctheisen-rocket** [IBM/db2forzosdeveloperextension-about#106]
I have installed the newest version of Db2 Developer Extension (release June 23, 2023) under VS Code 1.79.2. with Windows 10 (10.0.19044.3086)

Configured a Db2 connection to a Db2 13 data sharing group and a connection to a tuning services server. 
Assigned this tuning services connection and a tuning profile to the Db2 connection.
Created a new simple SQL script, right clicked in the editor window and selected "Run SQL Options".
An error message pops up:
"Converting circular structure to JSON --> starting at
object with constructor 'TLSSocket' | property
'_httpMessage'-> object with constructor 'ClientRequest'
--- property 'socket' closes the circle

See attached screenshot.
![TuningServices_error](https://github.com/IBM/db2forzosdeveloperextension-about/assets/138218802/97c09c17-69b8-4cf7-b7f2-c0514cf78aad)

**Comment by katsoohoo** [comment]
Hi @ctheisen-rocket,

Thank you for reporting this issue. Can you let us know what version of the extension you are using and also [provide the extension's logs](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs)?

**Comment by ctheisen-rocket** [comment]
Hi, after stopping and starting the Tuning Services server as well as VS Code the problem disappeared. Thanks for your attention.

**Comment by ctheisen-rocket** [comment]
Closing the issue
