### ISSUE TITLE
Stored Procedure Builder for External Stored Procedures Missing Load Module Generation

### ISSUE THREAD

**Issue by eric5g** [IBM/db2forzosdeveloperextension-about#107]
We use the Stored Procedure Builder to create external stored procedures.  When using this feature in the DB2 Developer Extension it indicates that it has successfully deployed.  When we run the stored procedure, it fails because it cannot find the load module.  The only thing the store procedure builder is doing is defining the stored procedure to DB2 but it is not generating the load module that is needed at run time.  The Data Studio Stored Procedure Builder creates the load module and defines the stored procedure to DB2.  It does so, in part, by calling REXX exec DSNTPSMP.  The current stored procedure builder, in the DB2 Developer Extension, for external procedures is not a workable solution without the load module generation.

## Development environment where the bug occurred

- Db2 Developer Extension version: Most Current Released 06/23/2023
- Editor platform
  - [X ] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version:
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7):
- Java Version (Run `java -version` and paste the details here):
- Db2 for z/OS version (including function level for Db2 12):
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: Yes/No

## Problem description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior

-

### Expected behavior

-

**Comment by katsoohoo** [comment]
Hi @eric5g,

Thank you for bringing up this requirement. We will look into enhancing our current stored procedure deployment feature to include a more support for external stored procedures.

**Comment by katsoohoo** [comment]
Hi @eric5,

We will change the label from bug to enhancement since this is a feature that is not supported currently.

**Comment by equalchenbj** [comment]
We added support for creating and deploying an external SQL stored procedure in version 2.1.5. Check the guide [here](https://ibm.github.io/db2forzosdeveloperextension-about/docs/working-with-stored-procedures/creating-external-SQL-stored-procedures.html). Closing this issue. Feel free to reopen it if you have further questions.
