### ISSUE TITLE
Character encoding problem on the display of the results of a SELECT query

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#11]
Our Db2 systems are declared with EBCDIC IBM-1147 encoding.

We notice that French accented characters are incorrectly rendered in the display of the results of read requests (SELECT).

![db2de-encoding-1](https://user-images.githubusercontent.com/63861965/97689551-079ecc80-1a9c-11eb-899a-a0a1edd2b9ca.png)

![db2de-encoding-2](https://user-images.githubusercontent.com/63861965/97691716-028f4c80-1a9f-11eb-9da5-3eb76077504e.png)

[db2de-encoding-3_log.txt](https://github.com/IBM/db2forzosdeveloperextension-about/files/5464373/db2de-encoding-3_log.txt)

**Comment by realkendrickren** [comment]
@FALLAI-Denis thanks for reporting the issue. We are looking into the issue, and will let you know soon.

**Comment by realkendrickren** [comment]
@FALLAI-Denis we just published a new version v0.5.1 for this issue a few minutes ago, would you give a try?

**Comment by FALLAI-Denis** [comment]
it's now ok in version v0.5.1.

Thanks.

**Comment by FALLAI-Denis** [comment]
Solved in v0.5.1.
