### ISSUE TITLE
Failed to find keytar module for managing passwords on newer VS Code

### ISSUE THREAD

**Issue by abartlett** [IBM/db2forzosdeveloperextension-about#111]
## Development environment where the bug occurred

- Db2 Developer Extension version: 2.1.2
- Editor platform
  - [X ] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version: 1.83.0
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): Windows 11 (10.0.22621.2361)
- Java Version (Run `java -version` and paste the details here): IBM Semeru Runtime Open Edition 17.0.8.1 (build 17.0.8.1+1)
- Db2 for z/OS version (including function level for Db2 12): n/a
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: Yes/No No

## Problem description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior
- Launched extension
- Attempted to add connection 
- Got error.

### Expected behavior
- Launch extension
- Able to add connection

**Comment by stGoed** [comment]
I have the same issue when loading the extention:

Failed to find keytar module for managing passwords.

**Comment by COBOL-Erik** [comment]
Same here! Please fix this!

**Comment by scotdb** [comment]
Also a problem here, preventing use of the extension.

In addition to the issue with adding new connections, all existing connection details have been removed.

**Comment by scotdb** [comment]
See release note for VS Code 1.83 to see details of why this is happening (keytar has been removed) and recommended action (switch from keytar to SecretStorage API).

https://code.visualstudio.com/updates/v1_83

**Comment by katsoohoo** [comment]
Hi everyone, thanks for reporting this issue. We will provide a fix for this soon.

Workaround for now is to use the previous [VS Code version 1.82](https://code.visualstudio.com/updates/v1_82).

**Comment by ibmrcruicks** [comment]
flagged since 1.80 in June
https://code.visualstudio.com/updates/v1_80#:~:text=This%20release%2C%20we've%20started,our%20dependency%20on%20keytar%20altogether.

**Comment by FALLAI-Denis** [comment]
See:
* #102

**Comment by katsoohoo** [comment]
> flagged since 1.80 in June https://code.visualstudio.com/updates/v1_80#:~:text=This%20release%2C%20we've%20started,our%20dependency%20on%20keytar%20altogether.
> 
> Does Db2 extension use keytar directly, rather than the VSCode SecretStorage API?

We initially used keytar in our earlier releases, then moved to SecretStorage API in later releases. However, we kept keytar in order ensure we move existing secrets to SecretStorage API. We will provide a more detailed doc when the fix is released.

**Comment by katsoohoo** [comment]
We've just published Db2 Developer Extension 2.1.3 that should resolve the incompatibility with VS Code 1.83.0.

FYI, if you're doing a big leap version leap with Db2 Developer Extension, credential information may need to be re-inputted again. See [Usage problems related to changes in keytar support](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/usage-problems-related-to-changes-in-keytar-support) for more information.

**Comment by scotdb** [comment]
Excellent news.

I'm just heading to IDUG at the moment, but will try it out as soon as I am
back.

Phil
