### ISSUE TITLE
Not getting new connection

### ISSUE THREAD

**Issue by vidhyanamini10** [IBM/db2forzosdeveloperextension-about#112]
i have installed IBM DB2 z/OS developer extension 
while making new connection i am getting the below error .. is there any solution for this 

"Error running command connectionProvider.add: command 'connectionProvider.add' not found. This is likely caused by the extension that contributes connectionProvider.add."

**Comment by ibmrcruicks** [comment]
#111  causes this

**Comment by katsoohoo** [comment]
Closing this as #111 has resolved the issue.
