### ISSUE TITLE
TS014577032 - customer request re saving password in the configuration

### ISSUE THREAD

**Issue by craitaka** [IBM/db2forzosdeveloperextension-about#114]
The customer uses IBM MFA in order to authenticate, so the password can change multiple times a day. Is there a way to configure a tuning server without saving the password in the configuration?

The customer provided a screenprint in ecurep
https://ecurep.mainz.de.ibm.com/ae5/#id=TS014577032

**Comment by katsoohoo** [comment]
Hi @craitaka,

Thanks for opening the issue. We will look into adding an option to not save the password for tuning servers in a future release.

**Comment by katsoohoo** [comment]
Hi @craitaka, we have added an option to not save the tuning server password in our latest release v2.1.4. Please give it a try.

**Comment by equalchenbj** [comment]
Closing this issue as the request has been addressed since version 2.1.4.
