### ISSUE TITLE
Can't view Stored Procs with version that includes dots e.g. "V1.0.0"

### ISSUE THREAD

**Issue by xApt-George** [IBM/db2forzosdeveloperextension-about#116]
## Development environment where the bug occurred

- Db2 Developer Extension version:
- Editor platform
  - [x] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version: 1.84.1
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): Windows 10
- Java Version (Run `java -version` and paste the details here): 17.0.5 2022-10-18 LTS
- Db2 for z/OS version (including function level for Db2 12):
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

## Problem description

Many of the Stored Procedures I'm working with use the versioning Vx.x.x which can't be opened up using the catalog features in the extension.

Detailed steps for reproducing the problem:

1. First step
Create a Stored Procedure where Version = "V1.0.0"
### Observed behavior
When trying to click on the Stored Procedure from the new catalog features I get a message saying:
SCHEMA.SP_FETCH_DATA.V1.0.0 stored procedure is invalid.
The expected format is schema.specificname or schema.specificname.version
-

### Expected behavior
I can open up the Stored procedure and see its properties like I can if the Version is "V1" for example
-

**Comment by katsoohoo** [comment]
Hi @xApt-George,

Thank you for reporting this bug. We'll look into this.

**Comment by katsoohoo** [comment]
Hi @xApt-George, we've just released v2.1.4 that fixes this issue. Please try it out and let us know if your problem has been resolved.

**Comment by xApt-George** [comment]
Hi I've just tried out the latest release and this has resolved the issue thank you very much for the speedy turn around!
