### ISSUE TITLE
TMSREP0007E: tuning connection profiles could not be retrieved

### ISSUE THREAD

**Issue by stGoed** [IBM/db2forzosdeveloperextension-about#117]
- Db2 Developer Extension version: 2.1.3
- Editor platform
  - [x] Visual Studio Code
- Editor platform version: 1.82.3
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): Windows
- Java Version (Run `java -version` and paste the details here):
java -version
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.382-b05, mixed mode)
- Db2 for z/OS version (including function level for Db2 12): Db2 12
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

## Problem description

After defining the SQL Tuning Services Server I'm trying to add a tuning connection profile as described here:
https://ibm.github.io/db2forzosdeveloperextension-about/docs/tuning-sql-queries/advanced-tuning-environment-options.html#creating-a-tuning-connection-profile

However when I right-click and select "Show Tuning Connection Profiles" I get the error message:

`The tuning connection profiles could not be retrieved: TMSREP0007E: The repository connection was not specified. Specify the repository connection before running a tuning action.`

nothing is shown in the log or output
Last message shown there is INFO  -- Generating token for user :  <userid>
when I completed the config of the server

thx,
Steven

**Comment by katsoohoo** [comment]
Hi @stGoed,

Based on the error message, you may need to do some additional setup for the SQL Tuning Services server before using it in the extension.

Can you verify if you have done **Part 1** and **Part 2** in [Getting started with SQL Tuning Services](https://www.ibm.com/docs/en/db2-for-zos/13?topic=services-getting-started)?

**Comment by stGoed** [comment]
Indeed, Part 1 was skipped.
it is working now, thx
