### ISSUE TITLE
SQLERROR -302 when using host-variables in the query

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#12]
SQLERROR -302 error occurs when executing a query using host-variables

```
-302                                                                             
 THE VALUE OF INPUT VARIABLE OR PARAMETER NUMBER position-number IS INVALID OR  
 TOO LARGE FOR THE TARGET COLUMN OR THE TARGET VALUE          
```   

![db2de-error-302-1](https://user-images.githubusercontent.com/63861965/97692952-bba25680-1aa0-11eb-8bc8-79142ad47965.png)

![db2de-error-302-2](https://user-images.githubusercontent.com/63861965/97692958-bf35dd80-1aa0-11eb-9845-a53b688373bd.png)

![db2de-error-302-3](https://user-images.githubusercontent.com/63861965/97692979-c4932800-1aa0-11eb-974b-26d66a6ecc34.png)

![db2de-error-302-5](https://user-images.githubusercontent.com/63861965/97693527-96faae80-1aa1-11eb-96dd-c930ae18d27e.png)

[db2de-error-302-4_log.txt](https://github.com/IBM/db2forzosdeveloperextension-about/files/5464413/db2de-error-302-4_log.txt)

**Comment by realkendrickren** [comment]
@FALLAI-Denis when you provide the input value for the host variable/parameter marker for string types, like CHAR, VARCHAR, etc, do NOT put quote around the value, otherwise, the quote itself will be taken as the part of the value, which is why you got -302 for the value too long.

Please try to only put CTRS for :CBAS variable, and S9Q100 for :CENT.

**Comment by FALLAI-Denis** [comment]
By entering the string type parameters without delimiter, the query is executed correctly.

On the VS Code Marketplace website, there is an example of entering string type parameters. But on my personal installation, the gif image of the example is not rendered.

I will suggest specifying how to enter parameters in the user documentation.

I close this issue.
