### ISSUE TITLE
Formatter does not handle ^= (Not equal) properly (<> works)

### ISSUE THREAD

**Issue by ThomasLieser** [IBM/db2forzosdeveloperextension-about#122]
In Version 2.1.4 the formatter does not recognize ^= 
It will put a blank between the two characters. The <> notation works

**Comment by FALLAI-Denis** [comment]
Hi,

According to the [Db2 for z/OS, basic predicates](https://www.ibm.com/docs/en/db2-for-zos/12?topic=predicates-basic-predicate) reference documentation, the `^=` operator does not appear to be explicitly supported, and appears to be a derived form of the `!=` operator, or the `¬=` operator, and could depend on the characters encoding used.
Although this operator may be supported, its use is not encouraged. 
Personally I have never seen it used in several decades of using Db2 for z/OS.

What codepage do you use on mainframe to code your source programs?
How is the sequence `^=` rendered if you browse a DBRM (by requesting a UTF-8 display)?

**Comment by katsoohoo** [comment]
Thanks for the background @FALLAI-Denis. We'll look into this as well @ThomasLieser.

Happy Holidays!

**Comment by FALLAI-Denis** [comment]
Hi,

As for request #121, it is necessary to take into account the encoding used on the mainframe and its interpretation after local transfer.

```
Hex     037  1147
-----  ----  ----
x4C6E   <>    <>
x5A7E   !=    §=
x5F7E   ¬=    ^=
xB07E   ^=    ¢=
```

**Comment by ThomasLieser** [comment]
misunderstanding on my side - solved - thanks for the help

**Comment by ThomasLieser** [comment]
reopened to give the team the time to react
see https://github.com/IBM/db2forzosdeveloperextension-about/issues/121

**Comment by equalchenbj** [comment]
@ThomasLieser ^= can be recognized in version 2.1.5. Closing this issue. Feel free to reopen it if you have further questions.
