### ISSUE TITLE
Unable to connect to DB2.

### ISSUE THREAD

**Issue by Farrenzo** [IBM/db2forzosdeveloperextension-about#127]
I get the error: `Failed to connect to DEV: Unable to set DB2 version information: DB2 SQL Error: SQLCODE=-440, SQLSTATE=42884, SQLERRMC=GETVARIABLE;FUNCTION, DRIVER=4.29.24` when I finish setting up a connection and click on finish.

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/6978980/92b26a18-264c-4ec8-80e6-21a8d4c26270)

Is it possible to pass the connection string manually within the settings?

**Comment by equalchenbj** [comment]
Hi Farrenzo, thank you for reporting this issue. It seems that your database doesn't have [GETVARIABLE](https://www.ibm.com/docs/en/db2-for-zos/13?topic=functions-getvariable) function set up. Could you check it? You can run this query to see if the function is available. 
`SELECT GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1`

**Comment by Farrenzo** [comment]
You are correct, it is indeed not set up. I get the same error when I query for the `GETVARIABLE`.

**Comment by equalchenbj** [comment]
@Farrenzo Could you try to add explicit schema to GETVARIABLE when run this query? Thanks.
`SELECT SYSIBM.GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1`

**Comment by Farrenzo** [comment]
Unfortunately, I am no longer in a position to troubleshoot this issue.

**Comment by arronlacey** [comment]
I'm getting the same issue and can help debug this. I have ran  `SELECT SYSIBM.GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1` and on specific schemas, but I get:

`SQLERROR[42884]: No authorised routine named 'GETVARIABLE' of type 'FUNCTION' having compatible arguments found. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.26.14`

**Comment by arronlacey** [comment]
I can retrieve the DB2 version however by doing:

```
SELECT service_level, fixpack_num FROM TABLE
(sysproc.env_get_inst_info())
as INSTANCEINFO
```
