### ISSUE TITLE
Catalog navigation - No statements on REST Services packages

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#128]
## Development environment where the bug occurred

- Db2 Developer Extension version: 2.1.4
- Editor platform
  - [X] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version: 1.85.1
- Operating system on which your editor runs: Windows 10 Enterprise 22H2 x64
- Java Version: Java 17
- Db2 for z/OS version: Db2 12 / Db2 13
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: Yes 
[IBMDb2ZosDeveloper_RESTServices.txt](https://github.com/IBM/db2forzosdeveloperextension-about/files/13961078/IBMDb2ZosDeveloper_RESTServices.txt)

## Problem description

Detailed steps for reproducing the problem:

1. Connect to Db2 system
2. Expand to see the different types of objects in the catalog
3. Select “REST Services”
4. Click on link (name) of a REST Service to access its details
5. In the Properties, click on a link to the associated Package to access its details
6. Access the “Statements” tab on Package 

### Observed behavior

Message "no statements found"

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/63861965/1b7b9b39-715c-41b8-a8e1-4a24894ae075)

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/63861965/c9d88821-5f06-4a1a-8efc-2ead4d21f9b4)

“Properties” and “Dependencies” are well populated.

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/63861965/2c313f8b-1b05-4691-99f7-ff5f4303c9fc)

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/63861965/b193bf4e-957a-44af-a6a8-a6dd86e59ee8)

Access to Statements from other packages (COBOL programs in general) works without problem.

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/63861965/200d0ec9-d0fd-4860-b4c1-260f4205ef57)

### Expected behavior

Display statement(s) of Package for REST Service.

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/63861965/1e74890c-1b70-4601-8f61-57c49ba2a572)

![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/63861965/fe5fb030-4395-468a-913f-6a065f865adc)

Thanks.

**Comment by amadhavia** [comment]
Thanks @FALLAI-Denis for reporting this. We will look into this.

**Comment by equalchenbj** [comment]
@FALLAI-Denis We have fixed this bug in version 2.1.5. So I'm closing this issue. Feel free to reopen it if you have further questions.
