### ISSUE TITLE
Add Additional Configurations At Connection Level

### ISSUE THREAD

**Issue by scotdb** [IBM/db2forzosdeveloperextension-about#13]
It would be good to bring over some of the "Run Options" into the connection definition. 

On Data Studio I have one connection defined per qualifier / schema / SQLID.  Sometimes I would prefer to have a separate connection per database, but you can't do that in Data Studio (the filters you set up at a connection level aren't really z/OS oriented). 

As a starter it would be good to set the CURRENT SQLID as a parameter of the connection (after all you set it on the JDBC connection string). 

Another one which I need all the time is "CURRENT DEBUG MODE" : otherwise I've got to add extra clauses to my stored procedure code when building which I need to take out for deployment to production.

**Comment by realkendrickren** [comment]
@scotdb thanks a lot, Philip. This is indeed one of items that we plan to support in future.

**Comment by realkendrickren** [comment]
This one is also mentioned in #10

**Comment by realkendrickren** [comment]
@scotdb Hi Philip, we just published a new version (0.5.5) of the extension today. The new version has full support on JDBC properties, by which you can define currentSchema, currentSQLID, and others at the connection level. Please upgrade the extension in VSCode and give a try.

BTW, DEBUG MODE is going to be taken care of in future.
