### ISSUE TITLE
No authorised routine named 'GETVARIABLE' of type 'FUNCTION'

### ISSUE THREAD

**Issue by arronlacey** [IBM/db2forzosdeveloperextension-about#136]
I'm getting the following issue when connecting to an IBM DB2 database:

`SQLERROR[42884]: No authorised routine named 'GETVARIABLE' of type 'FUNCTION' having compatible arguments found. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.26.14`

I am testing this for the first time on a Windows 10 system and installing using the .VSIX file as it's an air gapped environment. Install seems fine but when entering all of the details in to connect I get the above error. I can also confirm the I cannot find any function called "GETVARIABLE" when using the database in Eclipse.

**Comment by equalchenbj** [comment]
@arronlacey Thank you for provide this information. We have open an issue internally to track this problem. I'll let you know the progress.

**Comment by equalchenbj** [comment]
@arronlacey Could you confirm that your connection is DB2 for z/OS? We need to clarify that this tool only supports DB2 for z/OS. But I think we still need to provide the correct information for users.

**Comment by arronlacey** [comment]
ah it's LUW - sorry!

**Comment by equalchenbj** [comment]
> ah it's LUW - sorry!

Thank you. It's helpful for us to know that a user may not know the database type.
