### ISSUE TITLE
Unable to enter Hex values for Host variables through IDz

### ISSUE THREAD

**Issue by exoboosters** [IBM/db2forzosdeveloperextension-about#138]
I have a customer who is using Db2 for z/OS extension via IBM Developer for z/OS v16.0.3. When attempting to execute a query that has host variable a pop-up window appears, the data for the host variable is a hexadecimal value. The field doesn't accept Hex values resulting in an error (SQLCODE=-302) and the query does not execute.

## Development environment where the bug occurred

- Db2 Developer Extension version: unsure, part of IDz v16.0.3
- Editor platform
  - [ ] Visual Studio Code
  - [ ] Eclipse Theia
  - [x] IBM Developer for z/OS
- Editor platform version: 16.0.3
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): Windows 10
- Java Version (Run `java -version` and paste the details here):
- Db2 for z/OS version (including function level for Db2 12): v12 FL509
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

### Background:
Data in a field in the table is defined as a 4-byte character, but the data is actually hexadecimal values, not necessarily readable EBCDIC characters. As an example, the field might contain `x'918FFB1A'`. The following screenshots show the actions performed & results from the IDz window.

![sql-1](https://github.com/IBM/db2forzosdeveloperextension-about/assets/26982983/53aa953a-3515-4511-898f-9f295c95ab4a)

![sql-2](https://github.com/IBM/db2forzosdeveloperextension-about/assets/26982983/73188373-f22c-4811-8849-d2853f0d4f08)

### Observed behavior

- Executing the query results in an error with Return Code -1, SQLCODE=-302, SQLSTATE=22001 (value provided is too long for the column)

### Expected behavior

- The rows that meet the criteria of the select query should be displayed.

**Comment by jwflicker** [comment]
Some questions that may help move this issue along:
 - Do we know the DDL for the table and column being queried?
 - Do we know if this could be performed in IBM Data Studio?
 - Do we know if this can be done using the JDBC driver?  Do we have an example?

**Comment by b-tsao** [comment]
To continue this from @jwflicker 
- I assume the query is some table that has a column of CHAR(4)
- After checking data studio I could not find a similar feature
<img width="1303" alt="image" src="https://github.com/IBM/db2forzosdeveloperextension-about/assets/8595654/5a4748d5-85ff-4993-b1b7-d78e5a237f38">
- I do not believe this can be done with the JDBC driver

I believe this is not a bug and should be changed to enhancement request.

**Comment by b-tsao** [comment]
@exoboosters

@equalchenbj found that you can use BINARY datatype to pass in the hex value to retrieve the desired output
Example:
<img width="1398" alt="image" src="https://github.com/IBM/db2forzosdeveloperextension-about/assets/8595654/8d1c51d1-ada9-4075-924e-f3310d68aca8">
<img width="1323" alt="image" src="https://github.com/IBM/db2forzosdeveloperextension-about/assets/8595654/6e3d9304-3a8c-46b9-bf16-b28b519c694b">

**Comment by exoboosters** [comment]
Thank you @b-tsao I don't believe BINARY is an option on the IDz screen. The `Data Type` field would need an additional drop down option for Binary.

**Comment by jwflicker** [comment]
@exoboosters "Binary" is indeed an option when selecting the type of host variable or parameter marker value.  You can pass in a hexadecimal values into it, repeating the example displayed above.
<img width="662" alt="Screenshot 2024-05-15 at 11 47 44 AM" src="https://github.com/IBM/db2forzosdeveloperextension-about/assets/9770138/705d1cab-cc60-45d1-96ab-066fbfc4f200">
<img width="699" alt="Screenshot 2024-05-15 at 11 47 27 AM" src="https://github.com/IBM/db2forzosdeveloperextension-about/assets/9770138/4ca2c893-cfda-4bd0-b554-72f60df71311">

**Comment by exoboosters** [comment]
Thank you. I mis-stated earlier that it wasn't available in IDz. Appreciate your help @b-tsao and @equalchenbj. I am closing this.
