### ISSUE TITLE
After connecting to a Db2 database and viewing Db2 table data in IDz v16 with Db2 for z/OS not showing the data in proper format.

### ISSUE THREAD

**Issue by Chetan03899** [IBM/db2forzosdeveloperextension-about#149]
- Db2 Developer Extension version:  IDz v16 with Db2 for z/OS
- Editor platform: IBM developer for ZOS version 16.0.4
- Editor platform version:
- Operating system: Windows 11
- Java Version: Version 8
- Db2 for z/OS version (including function level for Db2 12):  Db2 for z/OS Tooling	1.0.0.202403131333
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

## Problem description
After connecting to a Db2 database and viewing Db2 table data in IDz v16 with Db2 for z/OS it is not showing the data in proper format, and when we view the same table data in the SPUFI, it is coming in as expected.

Detailed steps for reproducing the problem:

1. We are Connecting to a Db2 database and viewing Db2 table data in IDz v16 with Db2 for z/OS by referring the following guide by IBM :  https://community.ibm.com/community/user/ibmz-and-linuxone/blogs/chris-sayles1/2024/02/08/connecting-to-a-db2-database-and-viewing-db2-table?communityKey=f461c55d-159c-4a94-b708-9f7fe11d972b

Scenario explanation:
Let's take the below as a sample table (the below snippet is not related to the actual issue, just used to explain the scenario):
![image](https://github.com/IBM/db2forzosdeveloperextension-about/assets/175298707/7cab0e05-f490-4215-960a-c80b473c384c)

In the above snippet, we are viewing the CUST DATA table for field LNAME, which is showing properly as expected, and it will also show the same format in the SPUFI if we check.

Actual issue: For example, when we are viewing the ABC table in the IDZ for FIELD1, we are not getting the correct data as it is showing in the SPUFI. It is giving squares instead of blank spaces and giving the @ instead of that character.

### Observed behavior
Giving squares instead of blank spaces 
Its giving the @ instead of that character.

### Expected behavior
Should be blank spaces and actual character.

**Comment by jwflicker** [comment]
The customer has reported seeing unprintable characters in their results.  But i suspect we need information about how the codepages were setup for Db2 and what the actual column values in the database are.  Can you attach screenshots of the relevant DDL statements and details about the data involved.

Can you also attach the relevent query result file from your workspace?
To do this, reproduce the issue, then right click on teh Db2 Connection and select properties, navigate to the Tracing tab, and press the Show Logs button:
<img width="914" alt="Screenshot 2024-07-11 at 10 41 19 AM" src="https://github.com/IBM/db2forzosdeveloperextension-about/assets/9770138/5320660e-fd87-49ba-95a7-a36948512c17">

In the Finder, go up one level and go into the queryResults folder.  Find the most recently created file and send that to us.
<img width="386" alt="Screenshot 2024-07-11 at 10 41 32 AM" src="https://github.com/IBM/db2forzosdeveloperextension-about/assets/9770138/38e97c11-3618-45d7-9e4d-f92d49537653">

**Comment by Chetan03899** [comment]
Hi @jwflicker We have shared all the request details under the TS015413679 IBM case for the same issue. Kindly get in touch with Fernando Pedraza from IBM for the requested details and documents. If any further information is required, please let me know.

**Comment by jwflicker** [comment]
I'm going to close this as we shouldn't be referencing internal customer tickets on a public github page.
We can try and move this communication to an alternative internal channel where it may get more attention
