### ISSUE TITLE
Associate Default Connection with a Directory / Workspace

### ISSUE THREAD

**Issue by scotdb** [IBM/db2forzosdeveloperextension-about#16]
It's really annoying that you have to associate a connection with every file you create.

It would be great if there was the ability to specify a default connection.

But since we work across many systems / databases, where our code is organised into different directories / source code repositories, it would really be necessary to be able to define a default connection at either a directory or a workspace level.

**Comment by realkendrickren** [comment]
@scotdb thanks a lot for your feedback, Philip. We do plan to enhance this area and add more intelligence to avoid manual association operations as much as possible in future. Will keep you posted.

**Comment by realkendrickren** [comment]
@scotdb Hi Philip, we today just released a new version 0.5.5 in which we improved the logic on associating connections to SQL files. The extension will tend to use the same connection automatically from the same directory or workspace if you assign a connection to one of SQL files there before, there are also more intelligence added in this area, please upgrade the extension in VSCode and give a try.
