### ISSUE TITLE
Unable to specify JAVA Class reference pattern, when building JAVA Stored Procedures

### ISSUE THREAD

**Issue by jgantrii** [IBM/db2forzosdeveloperextension-about#161]
## Development environment where the bug occurred

- Db2 Developer Extension version: 2.1.17
- Editor platform: 
  - [ ] Visual Studio Code 1.93.0
- Operating system: Windows 10
- Java Version 1.8
- Db2 for z/OS version: V12R1M505

## Problem description

When building JAVA Stored Procedures using the IBM Data Studio there was a step where you had to specify a "JAVA Class Reference Pattern" as described in the following redpaper on page 77.  https://www.redbooks.ibm.com/redpapers/pdfs/redp4717.pdf  

We can't find that option in the Developer Extension. Is there another way to make this specifikation or is it not needed anymore?

**Comment by equalchenbj** [comment]
Hi @jgantrii Thank you for your question. Reference pattern is not needed for a dependency jar. You can give it a try. Let us know if you have further questions.

**Comment by DilipAgnihotriIBM** [comment]
Can we close this issue if you do not have further questions/concern.

**Comment by jgantrii** [comment]
Thanks for the response, you can close the case.
