### ISSUE TITLE
Add Database Object Explorer functionality

### ISSUE THREAD

**Issue by scotdb** [IBM/db2forzosdeveloperextension-about#17]
While the editing capabilities are great, a developer also needs to be able to browse the contents of a database as he works.

Some sort of Database Object Explorer, similar the the Data Source Explorer in Data Studio is therefore needed.   

However I would not model it exactly on this, as this view of the world has been influenced by the LUW catalog structure.  In particular it is important to add in the concept of a Db2 for z/OS database to the mix as a way of filtering lower level objects e.g. tablespaces / tables / indexes.   Obviously there are some objects that are cross-database and these would need to be put under their own hierarchies e.g. packages within collections, stored procedures within schemas etc.

Obviously there is a lot of functionality hanging off the Data Studio version which will take a while to develop.   But initially it would be good to drill down into objects - at least SG --> DB --> (TS -->) Table --> Columns / Indexes / Constraints etc.

**Comment by realkendrickren** [comment]
@scotdb this was also requested in #3, thanks a lot for raising this and sharing with us your thought, and it helps us much prioritize this one.

**Comment by FALLAI-Denis** [comment]
With sql code generator from table / view description in explorer Catalog ?

**Comment by danluksetich** [comment]
I'm interested in generating SQL and pulling stored procedure source from the system catalog preferably via an explorer type functionality

**Comment by nlopresti** [comment]
I would also agree. During general testing/troubleshooting we frequently run stored procedures. Today, we navigate through Data Studio to the schema that contains our procs and have the ability to run them. With the new enhancements to the plugin, we can right click, run stored procedure, but that requires us to have the source code open. 

Often times, some programs were created a long time ago by other individuals and in languages such as cobol. It would be extremely helpful to eliminate the need to open Data Studio to run stored procedures and do it all within vsCode. We are also testing the functionalities within Zowe Explorer if there is any opportunity there.

**Comment by BrianL674** [comment]
I agree that we need some type of db exploration.  I cannot seriously build SQL in this tool without having a visual reminder of the table names and table columns and indexes etc (Iike we have in Data Studio).  I often look at the properties and these object names to type them properly in my SQL editor.

**Comment by Marty850** [comment]
@katsoohoo can you say when we'll have a catalog browsing feature in VSCode Extension? Is it something we could expect in weeks, moths or years? ;-)

It would help us a lot in our company

**Comment by katsoohoo** [comment]
@Marty850 Catalog navigation is in the roadmap for 2022-23 :)

**Comment by katsoohoo** [comment]
Hi @scotdb,

We've added support to browse storage groups, databases, tables, and schemas in v2.1.0. Please give it a try!

**Comment by equalchenbj** [comment]
Closing this issue as the request has been addressed since v2.1.0.
