### ISSUE TITLE
Option for "clear query history" 

### ISSUE THREAD

**Issue by ssamayoa** [IBM/db2forzosdeveloperextension-about#170]
## Description of the feature or enhancement

Option for "clear query history"

**Comment by b-tsao** [comment]
Hi @ssamayoa, you can clear query history by right clicking any query history item and selecting delete all
<img width="366" alt="image" src="https://github.com/user-attachments/assets/fd5ad9f6-cb4b-43f2-8b46-70125bc18268">

**Comment by ssamayoa** [comment]
WTH!
I need to put attention!
In my defense I would expect to be alongside or instead of sort button.
Thanks!

**Comment by equalchenbj** [comment]
Close this issue as it's resolved.
