### ISSUE TITLE
SAF Check

### ISSUE THREAD

**Issue by Nithiyasubburaj** [IBM/db2forzosdeveloperextension-about#175]
## Development environment where the bug occurred

- Db2 Developer Extension version:
- Editor platform
  - [x] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version:
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7):
- Java Version (Run `java -version` and paste the details here):
- Db2 for z/OS version (including function level for Db2 12):
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: Yes/No

## Problem description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior
We tried connecting to z/OS Db2 using certificated, but getting below error message.

Failed to connect to  with message: C:\Users\\OneDrive - BNY\Desktop\db2 connect\DB2 Client Cert (Access is denied). ERRORCODE=-4499, SQLSTATE=08001

Please help me get this fixed
-

### Expected behavior

-

**Comment by equalchenbj** [comment]
I see the certification file is not accessible in the error message. Could you check if it's readable?
C:\Users\xbbjt95\OneDrive - BNY\Desktop\db2 connect\DB2 Client Cert (Access is denied)

**Comment by Nithiyasubburaj** [comment]
I have updated removed certificate location, still I'm getting below error:

Failed to connect to dsn3tsec.bnymellon.net/LOCDSN3: [jcc][t4][2043][11550][4.32.28] Exception java.io.IOException: Error opening socket to server dsn3tsec.bnymellon.net/167.113.55.131 on port 42,220 with message: toDerInputStream rejects tag type 45. ERRORCODE=-4499, SQLSTATE=08001

**Comment by Nithiyasubburaj** [comment]
![db2](https://github.com/user-attachments/assets/5696c7a6-cc6b-4c1c-adf4-ba1d85b58e37)

![db2](https://github.com/user-attachments/assets/f38a8f0c-aa6f-4ce7-873d-1e25573b2d23)
I have uploaded the properties,.. Please let me know if I'm missing something here.

**Comment by Nithiyasubburaj** [comment]
> I see the certification file is not accessible in the error message. Could you check if it's readable? C:\Users\xbbjt95\OneDrive - BNY\Desktop\db2 connect\DB2 Client Cert (Access is denied)

Please delete this post.

**Comment by Nithiyasubburaj** [comment]
> How did you set the connection properties in VS Code? In the command you use '-Djavax.net.ssl.trustStore=NUL' while in the VS Code it seems to use a different path. Is this a local path or on cloud? C:\Users\xbbjt95\OneDrive - BNY\Desktop\db2 connect\DB2 Client Cert

Please delete this post.

**Comment by Nithiyasubburaj** [comment]
I had this issue fixed. It was issue with the certificate. Thanks

**Comment by equalchenbj** [comment]
Glad to hear that. Close this issue as it's resolved.
