### ISSUE TITLE
Extension locks up when a lot of rows are returned

### ISSUE THREAD

**Issue by patbossman** [IBM/db2forzosdeveloperextension-about#18]
I wanted to mention that the extension locks up for larger than tiny result sets. Pull a few rows, no problem. Pull more than a few dozen it locks up. I have an RTS query that returns about 30,000 rows. No way we can run that in the extension. No you may ask, as I often do, are you actually going to look at all of those 30,000 rows. Well, most of the time no, but sometimes actually the answer is yes.

**Comment by danluksetich** [comment]
even more modest result sets.

**Comment by realkendrickren** [comment]
@danluksetich this is indeed in the list of the items that we plan for future. Thanks for bringing this up.

**Comment by realkendrickren** [comment]
@danluksetich Hi Dan, we just published v1.2.0, it allows users to specify the max number of rows returned for each executed SQL statement, it also contains many other enhancements, please upgrade and give a try. Thanks.
