### ISSUE TITLE
"Run" sql code with "IBM Db2 Database Plug-in for Zowe CLI"

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#2]
Hi,

Thank you for providing this extension which facilitates editing SQL source code.

What would be nice, would be to be able to execute SQL commands using "IBM Db2 Database Plug-in for Zowe CLI", for example according to the following implementation:
- right click in the source code
- "Run ..." in context menu
- sending the SQL source file to Db2 z / OS by the Zowe plug-in
- with request to produce the result in a file
- display of the result file in VS Code (plain text format)

[https://github.com/zowe/zowe-cli-db2-plugin](https://github.com/zowe/zowe-cli-db2-plugin)

**Comment by realkendrickren** [comment]
@FALLAI-Denis thanks a lot for trying the extension and the feedback. To be able to execute SQLs is part of our roadmap for future releases.

**Comment by realkendrickren** [comment]
@FALLAI-Denis I am now pleased to inform you that we have a new version 0.5 of Db2 developer extension published a few mins ago. This version provides "Run SQL with or without parameter marker/host variables" that you requested before. 

You can either download from https://marketplace.visualstudio.com/items?itemName=IBM.db2forzosdeveloperextension
or search "db2" in your VSCode extension view to upgrade/install the extension. The updated readme shows how the new features work.

Please feel free to try out and let us know your feedback.
