### ISSUE TITLE
[version 0.5.5]save results but the csv file got totally different content

### ISSUE THREAD

**Issue by fizbo-hp** [IBM/db2forzosdeveloperextension-about#21]
Hi, 
After update to version 0.5.5, I tried to save sql results to csv file. But it saved different content in it. It seems like that's the results I saved last time not the results I'd like to save now. Thanks.
The results I'd like to save now:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/75829550/101875211-347aef00-3bc5-11eb-953c-ba65740823b5.png">

The csv results:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/75829550/101875322-62603380-3bc5-11eb-8251-8d49cac6f59e.png">

**Comment by realkendrickren** [comment]
@fizbo-hp thanks for reporting this issue. This is a code bug, it was just fixed in v0.5.6, which was published today. Please upgrade the extension in your VSCode and give a try.
