### ISSUE TITLE
Choice of file name for storing queries configuration information: config.json

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#22]
The IBM Db2 for z/OS Developer extension stores configuration information for SQL command texts in a "config.json" file located in the same folder as the affected SQL files.

We think that the choice "config.json" is not discriminating enough and not clearly identified as being an element of management of the extension. It might even conflict with other extensions.

We propose to use a name clearly associated with its role and the fact that it is linked to the extension. Choosing this name should also place the file at the start or end of the list of other files in the folder, for example by prefixing it with a character "." .
The name could for example be ".db2zcnf.json".

Also see if the configuration information could be stored in a "zapp.yaml" or "zapp.json" file used by the IBM Z Open Editor extension.

**Comment by realkendrickren** [comment]
@FALLAI-Denis thanks for the feedback, we'll evaluate it.

**Comment by realkendrickren** [comment]
@FALLAI-Denis the enhancement is now addressed in v1.1.0 which we just delivered a couple minutes ago. The existing config.json will be automatically renamed and your existing settings suppose be kept in the new file. Please upgrade the extension in VSCode and give a try. 

I now close the issue, let us know if there is any question regarding this one.
