### ISSUE TITLE
Connections from settings.json

### ISSUE THREAD

**Issue by cmuncan** [IBM/db2forzosdeveloperextension-about#26]
one of my developers came back asking for an enhancement to have the connections be made available/picked up from settings.json

![image](https://user-images.githubusercontent.com/67800960/102403207-e6def780-3fb3-11eb-80b4-895450965df9.png)

this way you can then get the connections from here then it will be more predictable and easy to instruct anyone.  In addition to this, it would also allow for a simpler method of multiple connection handling

**Comment by realkendrickren** [comment]
@cmuncan can you please elaborate "have the connections be made available/picked up from settings.json"? Does it refer to putting the connection definition (like host, port, location, jdbc properties) into settings.json? Or does it refer to the connection usage (like which connection is connected and used for execution) into settings.json?

For the former one, the jdbc properties can be quite many, which may flood the settings especially when users have multiple connections defined in VSCode.

If the question is to locate where the connection definition is stored, there is a discussion in https://github.com/IBM/db2forzosdeveloperextension-about/issues/23, that you may want to check. In the same link, I also explained that we had a feature in our future to-do list to allow users to export the definition to share with others, that may address the part "more easy to instruct anyone" that you mentioned.

**Comment by cmuncan** [comment]
Hi Kendrick I've gone back to my user and his comments are:

"I want to pick up db2 connections from settings file which I can change as per my need .. and looks like that is possible from a json which should be in appdata folder"

![image](https://user-images.githubusercontent.com/67800960/102519899-15ff7280-4061-11eb-8959-2fc6451049ed.png)

the main issue is the password being saved.  we are unsure where it is being saved or how that can be incorporated with different connections.  for instance, you may have a different credential for DEV vs TEST vs UAT vs PROD

**Comment by realkendrickren** [comment]
Hi Chris, thanks. That is correct that your developer can customize the connections.json per need. 
The password is encrypted and stored in OS credential vault. On Windows 10, it is called Credential Manager, you can find the passwords under "Windows Credentials" category in that app. The passwords are associated with our extension, connection and user names, so if you have different connections for DEV/TEST/UAT/PROD, you can see that the differently credentials are kept separately correspondingly there.

**Comment by realkendrickren** [comment]
@cmuncan Hi Chris, I am closing this issue now. Please feel free to let us know or re-open if there is any further question in this area. Thanks.
