### ISSUE TITLE
csv export options in "Run options"

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#27]
It is possible to export the result of the execution of a query in a file in csv format.

The export options for csv format should be configured:
- by default in the extension parameters
- specifically for the execution options associated with a source file (query)

The csv options to be managed would be:
- conservation / deletion of spaces at the start and end of character strings for text fields
- management of numeric columns in numeric or in character string (currently in character string: not necessarily desirable)
- conservation / deletion of leading zeros at the start or end of a numeric value if exported in string format
- string delimiter character (not necessarily the one defined on the host system)
- field separator character (not necessarily the one defined on the host system)
- decimal mark character
- forcing of the sign on positive numerical values

For information, parameters managed on another Db2 export tool in csv format:
![Db2zfdev](https://user-images.githubusercontent.com/63861965/102526958-b7f08080-409c-11eb-93e7-abf74bb51139.png)

**Comment by realkendrickren** [comment]
@FALLAI-Denis thanks, we will evaluate this one.

**Comment by katsoohoo** [comment]
Hi @FALLAI-Denis,

In v1.3.1, we added some customizable export options such as changing the delimiter, and trimming leading and trailing whitespaces. Our [documentation](https://ibm.github.io/db2forzosdeveloperextension-about/docs/working-with-sql/saving-sql-results-to-a-file) has more information on the options. Please let us know what you think.

**Comment by equalchenbj** [comment]
Closing this issue as the request has been addressed in v1.3.1.
