### ISSUE TITLE
Problem of recognizing hosts-variables with COBOL names

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#28]
In an SQL query retrieved from a COBOL program, the hosts-variables are expressed in the form "prefix-name".
When this request is extracted from the COBOL program to make it a full-fledged ".sql" source, the hosts-variables are misinterpreted: only the "prefix" part is taken into account.

Example:
![image](https://user-images.githubusercontent.com/63861965/103661451-0e036600-4f6f-11eb-9b00-ce651b5240c9.png)

![image](https://user-images.githubusercontent.com/63861965/103662260-03959c00-4f70-11eb-9b70-2bff777b6050.png)

**Comment by realkendrickren** [comment]
@FALLAI-Denis the fix is now published, Please upgrade and give a try. I am now closing the issue.

**Comment by FALLAI-Denis** [comment]
Sorry, but apparently there is still a syntactic recognition problem with flag fields.
Because of these syntax errors, the query cannot be triggered.
![db2z001](https://user-images.githubusercontent.com/63861965/107116901-b8c0ba00-6876-11eb-92fa-c9dd5267f893.png)

**Comment by FALLAI-Denis** [comment]
In the absence of an indicator zone, the SQL syntax becomes correct, the query can be executed, and hots-variables with a hyphen in the name are recognized.
![db2z002](https://user-images.githubusercontent.com/63861965/107116948-1e14ab00-6877-11eb-9f92-7a816a624f02.png)

**Comment by FALLAI-Denis** [comment]
A problem with indicator areas:
![Hyphen_in_indicators](https://user-images.githubusercontent.com/63861965/107117157-8f089280-6878-11eb-86c7-97bd44cba682.gif)

**Comment by realkendrickren** [comment]
@FALLAI-Denis it seems that the problem happened when there were hyphens in the variables including indicators. Will take a further look.

**Comment by realkendrickren** [comment]
@FALLAI-Denis the above issues are now fixed in v1.1.0. Please upgrade the extension in VSCode and give a try. Thanks a lot again for using the extension extensively and reporting the issues/enhancements. Let me know if there is any further question.
