### ISSUE TITLE
Add a capability on VSCode to perform simple browse data

### ISSUE THREAD

**Issue by RegiBrazil** [IBM/db2forzosdeveloperextension-about#3]
Using IDz or Data Studio developers can easily perform a browse data of DB2 table contents.

It would be great having same capability with VSCode.

 
![Browse_Data](https://user-images.githubusercontent.com/31251235/92284266-ab6e6080-eecf-11ea-9f71-3d81e6ceafee.jpg)

**Comment by realkendrickren** [comment]
Thanks for trying it and the good feedback, @RegiBrazil 

We will evaluate it.

**Comment by spufidoo** [comment]
What about adding an EXPLAIN as well as an EXECUTE?

**Comment by realkendrickren** [comment]
@spufidoo thanks a lot for the feedback, both are in our roadmap for future releases.

**Comment by katsoohoo** [comment]
Hi @RegiBrazil,

We've added support to browse storage groups, databases, tables, and schemas in v2.1.0. Please give it a try!

**Comment by equalchenbj** [comment]
Closing this issue as the request has been addressed since v2.1.0.
