### ISSUE TITLE
How to run a query with an specific connection when I multiple ones?

### ISSUE THREAD

**Issue by LUCASMA96** [IBM/db2forzosdeveloperextension-about#30]
Hi,  First of all I would like to greet everyone involved, that's an awesome project. 

Now my question:

I've been testing the extension and it's working fine, but I normally work with more then one connection and I do not know how to set a query to run with an specific connection. 
For example: I have one connection for each environment (DEV, TEST and PROD). How can I set my query to run on, let say, DEV connection?

Thanks!

ps. My system is macOS Catalina

**Comment by realkendrickren** [comment]
@LUCASMA96 thanks for using this extension. 
You can find a connection name (or "no connection") on the status bar of VScode for the file you work on, click on the connection name, it'll prompt you with available connections you currently have on the top of editor (like VSCode command palette), then you can pick and choose which one you want to use to execute the SQLs later.

**Comment by realkendrickren** [comment]
Here is a screenshot to show you where you find the connection currently associated with the file (in this case, 'utec648.vmec.svl.ibm.com/STLEC1' is currently my connection):

![image](https://user-images.githubusercontent.com/26660024/105078372-e2e34100-5a5b-11eb-8b1d-3a85e18d6a96.png)

**Comment by LUCASMA96** [comment]
I've found it. Thanks a lot!!!

**Comment by realkendrickren** [comment]
Great. I am closing the issue now.
