### ISSUE TITLE
Error on Db2 SQL Service if multiple instances of VS Code are started

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#31]
The Db2 SQL service is started with a first instance of VS Code.

If another instance of VS Code is started, it tries to start another instance of the Db2 SQL service, which throws an error because the IP port is already in use.

All VS Code instances would have to share the same Db2 SQL service, (And the Db2 SQL service should only be unloaded when the last instance of VS Code is stopped, which assumes that the Db2 SQL service knows how to differentiate the different instances of VS Code).

If it is not possible to share the Db2 SQL service between several VS Code instances, then you must start as many Db2 SQL services and automatically change the IP port, (so define a range of IP ports to use and try them one by one until you find a free one).

[db2z instance 1.txt](https://github.com/IBM/db2forzosdeveloperextension-about/files/5973495/db2z.instance.1.txt)
[db2z instance 2.txt](https://github.com/IBM/db2forzosdeveloperextension-about/files/5973496/db2z.instance.2.txt)
![db2z005](https://user-images.githubusercontent.com/63861965/107802277-68a79300-6d61-11eb-96fe-c9b21cbc47f5.png)

**Comment by realkendrickren** [comment]
@FALLAI-Denis glad you brought this up. To let users define a range of ports is indeed on our plan.

**Comment by nlopresti** [comment]
I agree to this, all of my developers have multiple instances of vsCode running and only the first is able to utilize the sql service.

**Comment by theship** [comment]
To assist others with finding this issue, I'd like to add the error code I received in plain text. Restarting Visual Studio Code with multiple windows triggered the error:

> The Db2 SQL Service could not be started because the specified port (3330) is already in use.

I didn't know where the conflict was originating, and that it simply meant the service was already running in the other (first instance) window. So, thanks much, @FALLAI-Denis.

**Comment by realkendrickren** [comment]
@FALLAI-Denis @nlopresti @theship we just published v1.2.0, it is enhanced to allow multiple instances of VSC/extension uprunning via accepting multiple port numbers or port range or mix. This release also contains many other enhancements, please upgrade and give a try. Thanks.
