### ISSUE TITLE
Issue on MacOS running the debug stored procedure feature

### ISSUE THREAD

**Issue by nlopresti** [IBM/db2forzosdeveloperextension-about#34]
As requested by the team, we have identified an issue on the mac version of VSCode, preventing the debugger from successfully proceeding. 

We are working with IBM and our internal communication team to determine the cause.

**Comment by realkendrickren** [comment]
@nlopresti thanks a lot for opening the issue to track this. This will be fixed in a hotfix soon.

**Comment by realkendrickren** [comment]
@nlopresti we just published a hotfix v1.1.1 which fixed the issue. Can you please upgrade the extension in your VSCode and give a try? Let me know if there is any issue. 

Thanks!
