### ISSUE TITLE
Feature request - Ability to "remember" input parameters when running/debugging a stored procedure

### ISSUE THREAD

**Issue by nlopresti** [IBM/db2forzosdeveloperextension-about#35]
Hi team, it's become very tedious to continue to type in the input parameters when running/debugging. We have some stored procs that take in many parameters (10+) and it becomes time consuming to do so. Is there a way to have these params "save" in a config file for the next time the program is executed?

**Comment by realkendrickren** [comment]
@nlopresti thanks a lot for bringing this up, this is also an item on our plan. We will evaluate it.

**Comment by realkendrickren** [comment]
@nlopresti we just published v1.2.0, which can remember the history of input values and prefill the value for NSP parameters when running or debugging. It also contains many other enhancements, please upgrade and give a try. Thanks.
