### ISSUE TITLE
Support for additional Code Snippets

### ISSUE THREAD

**Issue by turnerm92** [IBM/db2forzosdeveloperextension-about#37]
The existing code snippets are great for developers, but as we move our DDL source control to Git our DBAs will also be using the extension. One of the key snippets currently missing that DBAs will benefit from is for Create Tablespace.

Others that I have found missing in my day to day activities is also Create Alias and Create Sequence, but tablespace would be the most useful given the number of options available.

On Create Table there are also missing prompts for very common options such as NOT NULL (WITH DEFAULT) on column definitions.

**Comment by realkendrickren** [comment]
@turnerm92 Hi Mark, thanks a lot for bringing up this one. We deliberately started with limited number of snippets, but we do want to hear more feedback in this area and keep adjusting and expanding with more frequently used ones. We will evaluate this.

**Comment by realkendrickren** [comment]
@turnerm92 just want to share with you an article we recently published, the article talks about how to add additional snippets by your own and make them work with the extension.  Please check out -> https://ibm.github.io/db2forzosdeveloperextension-about/2021/03/13/Tips-and-tricks.html

BTW, there are other articles published there, maybe useful to you too.

**Comment by katsoohoo** [comment]
FYI, here is the updated link for how to create your own snippets: https://ibm.github.io/db2forzosdeveloperextension-about/docs/tips-and-tricks/creating-your-own-code-snippets
