### ISSUE TITLE
Enable SQL syntax highlighting for SQL / DDL within a PDS member retrieved from z/OS

### ISSUE THREAD

**Issue by Clive-R-Harriss** [IBM/db2forzosdeveloperextension-about#4]
The SQL highlighting  provided by this extension works when I retrieve a sequential dataset with a low-level qualifier of SQL from my z/OS machine and highlights the contents - as below:
![image](https://user-images.githubusercontent.com/47148199/95465092-a12dff00-0972-11eb-9213-a0d2be2e50ab.png)

If I retrieve and open a member of a PDS from my z/OS machine containing the same code / contents then no highlighting occurs - as below:
![image](https://user-images.githubusercontent.com/47148199/95465238-c7ec3580-0972-11eb-8a37-47319f7ee503.png)

PDS members cannot contain a '.' in their name and renaming the member to end with the three chars 'SQL' does not trigger the highlighting in either case.

I also have the IBM zOpen Editor extension installed and this does highlight, say JCL, in members of a PDS where the PDS name has a low-level qualifier of 'JCL' 

Checking the docs on this I can see that file.associations have been used and the reason given is the same encountered by myself when opening a PDS member containing DDL/SQL
![image](https://user-images.githubusercontent.com/47148199/95465546-30d3ad80-0973-11eb-8016-bea780357af9.png)

Would it be possible to provide similar capabilities to those that exist in the zOpen Editor for associating PDS members in this extension?

**Comment by spufidoo** [comment]
Yo Clive. That's a VSCode issue. In your settings.json file, look for "files.associations" and include the following:
"*.SQL(*)": "sql",

**Comment by realkendrickren** [comment]
@Clive-R-Harriss thanks a lot for the comment. We will consider this in future, and @spufidoo (thanks) gave a good way to address this before that is available, can you try that?

**Comment by Clive-R-Harriss** [comment]
Hi Marcus exactly the point of my entry. On z/OS  PDS members do not have / cannot gave a .SQL LLQ. A sequential file with a LLQ of .SQL works I have used it.

What I think it needs is to allow a file association like that provided by the zOpen Editor for similar PDSs that contain JCL or COBOL source.

As zOpenEfitor is also developed by IBM it must surely be just a straightforward task to merge the required part in the code from that into this extension

**Comment by patbossman** [comment]
Hi Clive,
Yes, we're acknowledging we will change file associations in a future build.  You can also manually make a change right now if you like.  Thank you for your support!

**Comment by katsoohoo** [comment]
Hi @Clive-R-Harriss,

We looked into this and decided that we will likely not add the file association feature like Z Open Editor. The reason being that VS Code already provides this functionality with the [`file.associations` setting](https://code.visualstudio.com/docs/languages/identifiers) as @spufidoo has mentioned. Z Open Editor's file association feature is simply modifying VS Code's built-in `file.associations` setting. We feel adding an extra settings layer via our extension does not provide any value.

Please let us know if you still feel having a file association setting from our extension would still be useful for your case.

**Comment by katsoohoo** [comment]
I will be closing this issue as the solution is to use VS Code's `file.associations` setting. If there's a need to specify file associations at the extension level, feel free to re-open this issue.
