### ISSUE TITLE
Running SQL embedded in COBOL with line numbers

### ISSUE THREAD

**Issue by jkothurigithub** [IBM/db2forzosdeveloperextension-about#40]
Unable to execute the SQL where COBOL code as line number, neither able to execute with column selection

Errors on different approches
Column mode selection without line number
![image](https://user-images.githubusercontent.com/57986358/121653602-7f18ed80-caba-11eb-9bbc-c2896da82cb9.png)

same query with line number in between
![image](https://user-images.githubusercontent.com/57986358/121654018-e9ca2900-caba-11eb-9db8-abd818ab9e78.png)

Column mode selection with line number
 ![image](https://user-images.githubusercontent.com/57986358/121654199-19793100-cabb-11eb-8570-08394bc5c881.png)

**Comment by realkendrickren** [comment]
@jkothurigithub thanks for trying the extension. This feature is going to be available in the upcoming version, which will be out very soon, :-). Stay tuned.

**Comment by realkendrickren** [comment]
@jkothurigithub we just published v1.2.0, it supports to run selected SQL statement which is highlighted via column mode selection or multiple selection scope. Please give a try and let us know if you have other question. Thanks.

**Comment by jkothurigithub** [comment]
Thanks for quick release of solution in new version, column mode selection is working as desired.
