### ISSUE TITLE
Java runtime path is not configured correctly for the Db2 SQL Service extension

### ISSUE THREAD

**Issue by JohnPhilipPearson** [IBM/db2forzosdeveloperextension-about#49]
Windows version 10
Latest copy of VS Code
Installed db2forzosdeveloperextension
Created connection configuration to zOS Db2
Try to connect error:
Java runtime path is not configured correctly for the Db2 SQL Service extension.

On laptop is:
Location:
C:\IBM\InformationServer\jdk32\bin
![image](https://user-images.githubusercontent.com/5451681/126699662-28550829-6a14-4ebf-9182-39ecbc36e4b2.png)

**Comment by JohnPhilipPearson** [comment]
VS Code db2plugin settings were pointing to JAVA_HOME bin. Changed it to only the path. Now the error states "A 32-bit Java Runtime Environment is not supported for the Db2 SQL Service Extension.
![image](https://user-images.githubusercontent.com/5451681/126810638-06141c8a-1fd9-42cf-9091-dd6c9cca3e7d.png)

**Comment by b-tsao** [comment]
Hi @JohnPhilipPearson, thank you for using the extension and opening an issue!

In the first screenshot it seems the extension could not detect the Java your system uses. Based on your second screenshot you manually configured it in settings and it was able to find the Java, but unfortunately our extension only supports 64-bit Java as mention in our documentation https://github.com/IBM/db2forzosdeveloperextension-about#prerequisites-for-installing-db2-developer-extension.

Please try again with 64-bit Java and let us know if there are any further issues.

**Comment by JohnPhilipPearson** [comment]
We are using global desktop and administration installed 64 bit, here is what they installed and where:
![image](https://user-images.githubusercontent.com/5451681/129108675-8ee0a888-bc30-46da-9933-fcb9cab107d4.png)

This is the new error:
![image](https://user-images.githubusercontent.com/5451681/129108700-0641a93b-1570-438d-91b9-eaed3c390b2d.png)

**Comment by realkendrickren** [comment]
@JohnPhilipPearson the java path pasted above only contains 3 java executable file, it is not a full installation of jre, there is no library files (the necessary jre jar files) that a java application would require. Below is the screenshot from a sample environment with an installed jre:
![image](https://user-images.githubusercontent.com/26660024/129120882-94bb4728-ddfb-47c1-955c-913007f8be78.png)

Please follow the link provided in the readme to download and install either a JRE or a JDK.
