### ISSUE TITLE
Support TLS encryption / secure port

### ISSUE THREAD

**Issue by peterpk** [IBM/db2forzosdeveloperextension-about#5]
Connection wizard today has no way to make a TLS-encrypted connection to a Db2 secure port.  Please add entries in the wizard for these three JDBC parameters, and append them to the constructed URL:

- sslConnection (True/False)
- sslTrustStoreLocation (text for path name)
- sslTrustStorePassword (password entry)

**Comment by realkendrickren** [comment]
@peterpk thanks a lot for trying the extension and your feedback. The full support on JDBC properties is on going, we'll let you know once it is ready.

**Comment by realkendrickren** [comment]
@peterpk today, we just released a new version (0.5.5) of the extension that has full support of JDBC properties, you can define these SSL related properties with the version now. Please upgrade the extension in your VSCode to give a try.
