### ISSUE TITLE
Allow Ctrl+F to search SQL Results

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#50]
I noticed that I'm not able to search in SQL Results view with Ctrl+F.   
I'm not sure if it's a VS Code or a Developer Extension issue. Maybe you can add this functionality.

**Comment by katsoohoo** [comment]
Hi @Marty850,

In v1.3.1, we've added a search functionality to the SQL Results view. This can be used by clicking on the search icon to the left of the save icon.
![Screen Shot 2022-01-17 at 20 08 17](https://user-images.githubusercontent.com/5027555/149869494-f1d703cb-5d6b-401f-bb9f-e31f16c26c65.png)

**Comment by katsoohoo** [comment]
I will be closing this issue as the functionality has been added in v1.3.1.
