### ISSUE TITLE
Open "Result 1" tab in SQL Results view by default (for select statements)

### ISSUE THREAD

**Issue by Christoph-at-Github** [IBM/db2forzosdeveloperextension-about#55]
Currently after SQL execution the SQL Result view always shows us the "Status" tab. This of course is the most interesting tab, if a statement execution failed. But if a select statement executes successfully, we are mostly interested in the "Result 1" tab. So it would be a nice feature, if this tab will be opened by default (or there is a option within the settings to choose) after a successful SQL execution.

**Comment by realkendrickren** [comment]
@Christoph-at-Github That is a fair point, we'll evaluate it.

**Comment by katsoohoo** [comment]
Hi @Christoph-at-Github,

In v1.3.1, the SQL Results view will now show the Results tab by default if the execution was successful.

**Comment by katsoohoo** [comment]
I will be closing this issue as the functionality has been added in v1.3.1.
