### ISSUE TITLE
Add support for explain of selected SQL

### ISSUE THREAD

**Issue by Rune-Christensen** [IBM/db2forzosdeveloperextension-about#56]
Developers should allways explain their SQL before pushing to production, to avoid any performance issues.
We therefore request that the tool is extended with the possibility of getting a explain of a selected SQL.
This would make it easier for developers to adopt VS Code, if this feature is available in the same tool that they write their code.

**Comment by patbossman** [comment]
> Developers should allways explain their SQL before pushing to production, to avoid any performance issues. We therefore request that the tool is extended with the possibility of getting a explain of a selected SQL. This would make it easier for developers to adopt VS Code, if this feature is available in the same tool that they write their code.

You can explain SQL via the developer extension.  Has the visual explain resolved this issue, or is there something additional you wanted to see?

BTW - the tuning services are shipped with accessories suite and are rest enabled.  A significant reason for making the tuning services independent of vscode was to enable independent integration of the tuning services in customer automation, including as part of a CI/CD pipeline.  If you have a modern application development pipeline, you could capture explain as an artifact to be considered as part of the review and approval process.
