### ISSUE TITLE
Ignore line numbers in COBOL code

### ISSUE THREAD

**Issue by Rune-Christensen** [IBM/db2forzosdeveloperextension-about#59]
When working with COBOL code from a mainframe, there will often be linenumbers present in the source code.
![image](https://user-images.githubusercontent.com/26797797/132851433-22131c33-ed21-4ee1-b9e0-5b07ee64dd5c.png)
It would be nice if these are automatically ignored when trying to run the SQL.

**Comment by FALLAI-Denis** [comment]
You can select sql text in columns mode to ignore line numbers.

**Comment by katsoohoo** [comment]
As @FALLAI-Denis has mentioned, you can use [VS Code's column selection mode](https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection) to avoid selecting the COBOL line numbers.
