### ISSUE TITLE
Documentation - Java JRE required (not Java JDK)

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/db2forzosdeveloperextension-about#6]
Hi,

The extension's documentation states that the Java JDK is required and must be configured at the settings level:

`"db2forzosdeveloperextension.java.home": "C:\Program Files\Java\jdk1.8.0_181"`

In fact, only the Java JRE is required, (and the JDK is not necessarily available on the workstation):

`"db2forzosdeveloperextension.java.home": "C:\Program Files\Java\ jre8"`

I suggest modifying the documentation to refer to the JRE and not the JDK.

**Comment by realkendrickren** [comment]
@FALLAI-Denis that is correct, either JRE or JDK works. 

If you have JRE_HOME and JAVA_HOME environment variable in your system or profile, the extension will recognize that. We can improve the document on this part.

**Comment by realkendrickren** [comment]
@FALLAI-Denis we just released a new version (0.5.5) today, and explained JRE usage explicitly in the readme. Please upgrade the extension in VSCode and check out.
