### ISSUE TITLE
SSL connection from db2forzosdeveloperextension to Db2 on Z

### ISSUE THREAD

**Issue by krema03** [IBM/db2forzosdeveloperextension-about#64]
## Development environment where the bug occurred

- Db2 Developer Extension version: 1.61.0
- Editor platform
  - [x ] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version:
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): W10
- Java Version (Run `java -version` and paste the details here):
- java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
- Db2 for z/OS version (including function level for Db2 12): V12R1M505
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

## Problem description
I want to use a SSL connection to DB2 on z/OS, so I have the connection using the secure port, Option sslConnection=true....
It is getting to Db2 but the SSL handshake fails.. So I would like to know: is there a way I can give a certificate with the connection ? I looks like it does not automatically take the default certificates with its connection. This was also the case when I used DataStudio but there I can specify the certificate keystore/certificate

Detailed steps for reproducing the problem:

1. First step

### Observed behavior
message succesfull connection appears but connection is directly gone due to SSL handshake error

EZD1287I TTLS Error RC:  541 Initial Handshake 162             
  LOCAL: xx.xxx.xxx.xx..1487                                   
  REMOTE: xx.xx.xx.xxx..61717                                  
  JOBNAME: DB3UDIST RULE: DB0USecureServer                     
  USERID: DB0U GRPID: 0000004D ENVID: 00000783 CONNID: 15928514
-

### Expected behavior
succesfull connection
-

**Comment by katsoohoo** [comment]
Hey @krema03, you can specify JDBC properties like [`sslKeyStoreLocation` and `sslKeyStorePassword`](https://www.ibm.com/docs/en/db2-for-zos/12?topic=pdsdjs-data-server-driver-jdbc-sqlj-properties-db2-zos), or [`sslCertLocation`](https://www.ibm.com/docs/en/db2-for-zos/12?topic=pdsdjs-common-data-server-driver-jdbc-sqlj-properties-all-database-products) in the [**Optional** tab of the Db2 connection](https://ibm.github.io/db2forzosdeveloperextension-about/docs/the-basics/creating-a-database-connection).
