### ISSUE TITLE
Index Advisor functionality

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#74]
Hi,

it would be gerat to have a index advisor functionality in the tuning services like it's available in Data Studio.
Is there a plan to implement that in vs Code Extension/Tuning Services?

Kind regards
Martin

**Comment by patbossman** [comment]
Paid query tuning services APIs that integrate with both the developer extension and Admin Foundation are planned.

**Comment by katsoohoo** [comment]
Hi @Marty850,

Index Advisor is now available in v2.1.0. Please see [Software requirements for using the SQL tuning features](https://ibm.github.io/db2forzosdeveloperextension-about/docs/tuning-sql-queries/sql-tuning-requirements#software-requirements-for-using-the-sql-tuning-features) for more details.

**Comment by katsoohoo** [comment]
I will close this issue since the enhancement has been implemented in v2.1.0.
