### ISSUE TITLE
Switching between Tuning Results in Tuning History is not possible

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#77]
## Problem description

If you tune multiple sql statements and select the fist one in tuning history it's not possible to switch to the second via double click. It's only possible if you close the tab before.

We would expact that a new tab is opened if you click on another tuning history entry.

## Development environment where the bug occurred

- Db2 Developer Extension version: v1.3.4
- Editor platform
  - [x] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version: 1.62.1
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): Version 10.0.19042.1586
- Java Version (Run `java -version` and paste the details here): 1.8.0_321
- Db2 for z/OS version (including function level for Db2 12): V12R1M510
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

**Comment by katsoohoo** [comment]
Hi @Marty850,

Let me know if I'm understanding your issue correctly. Are you trying to view multiple Tuning Results at once? If so, opening Tuning Results currently behaviors the same as SQL Results where only view is opened in an editor group. To see multiple Tuning Results at once, you'll need to use [different editor groups like with SQL Results](https://ibm.github.io/db2forzosdeveloperextension-about/docs/working-with-sql/comparing-sql-results).

**Comment by Marty850** [comment]
Hi @katsoohoo, 
no we tried to see one result after another. So to recreate it tune two different sql statements. When the result of the second sql tuning ist open try to switch to the first one by double klick in the tuning history. You will still see the result of the second sql tuning.

**Comment by katsoohoo** [comment]
Hi @Marty850,

I'm having trouble re-creating the issue. Here are the steps I took:
1. Open SQL file with two statements.
2. Tune first statement.
3. **Tuning Summary** view appears and we leave it open.
4. Switch back to SQL file and tune second statement.
5. We get switched back to the **Tuning Summary** view and the content is for the second statement.
6. In **Tuning History**, expand the second statement and click **Statistics Advisor**.
7. The **Tuning Summary** view gets replaced by the **Tuning Results: Statistics Advisor**.
8. In **Tuning History**, expand the first statement and double-click **Visual Explain**.
9. The **Tuning Results: Statistics Advisor** view gets replaced by the **Tuning Results: Visual Explain** for the first statement.

Is there anything different you're doing when you hit the issue?

**Comment by Marty850** [comment]
Hi @katsoohoo,
it's the **Tuning Result** view where we get the problem not **Tuning Summary**. Try to swith between two tuning results in Tuning History ;-)

**Comment by katsoohoo** [comment]
Hi @Marty850,

Thank you for the clarification. I was able to recreate the issue now :). We will take a look at this.

**Comment by katsoohoo** [comment]
Hi @Marty850,

We've implemented a fix for this in v2.1.0. Please give it a try and let us know if the issue has been fixed.

**Comment by katsoohoo** [comment]
I will close this issue since the issues has been resolved in v2.1.0.
