### ISSUE TITLE
Documentation does not tell users how to update vscode to use jdbc drivers

### ISSUE THREAD

**Issue by johnottogood** [IBM/db2forzosdeveloperextension-about#79]
## Problem description
The section in the the Db2 Developer Extension readme regarding using JDBC jars does not tell there user where in VSCode you add the setting for the CLASSPATH.

 ```
   The IBM Data Server Driver for JDBC and SQLJ client license file 4.25.1301 or later

For information about locating and and enabling the client license file, see the following topic: 
https://www.ibm.com/support/pages/db2-jdbc-driver-not-licensed-connectivity-file-db2jcclicensecisuzjar-errorcode-4472-sqlstate42968

When you specify the location of the db2jcc_license_cisuz.jar license file in your VS Code settings (db2forzosdeveloperextension.db2sqlservice.dependencies), you must provide the full path.

```
1)  the above referenced URL doesn't really do anything to tell the user where to find the z/OS Db2 jdbc jars.   Fortunately I already know how.

2)  Now that I have the jars, where to I find the place to add db2forzosdeveloperextension.db2sqlservice.dependencies?    

### Expected behavior
Please give an example of setting the variable, and if semicolons or colons are needed (depending on platform)

**Comment by johnottogood** [comment]
I found this, which seems to be a good  link to add to the readme

**Comment by katsoohoo** [comment]
Hi @johnottogood,

Thanks for your suggestion on the documentation. `db2forzosdeveloperextension.db2sqlservice.dependencies` is a [VS Code setting](https://code.visualstudio.com/docs/getstarted/settings) that you can set with the [settings editor](https://code.visualstudio.com/docs/getstarted/settings#_settings-editor). We will work on making the documentation more clear on how to specify these settings.

**Comment by katsoohoo** [comment]
Hello @johnottogood,

We've updated the README with a [more informative link to find the client license file](https://github.ibm.com/mavericks/Web-IDE#prerequisites-for-installing-db2-developer-extension) and added a new section for [how to set the JARs in VS Code settings](https://github.ibm.com/mavericks/Web-IDE#setting-the-jdbc-license-and-jdbc-driver-files).

**Comment by katsoohoo** [comment]
Closing this issue as it has been updated with v1.4.
