### ISSUE TITLE
The Db2 SQL Service crashed 5 times - improve error handling when language server port is in use

### ISSUE THREAD

**Issue by patbossman** [IBM/db2forzosdeveloperextension-about#8]
The default port for the language server is 3000.  If the port is in use, the pop up error is that the server is crashing.  The logs do indicate that the port is in use, but it would be nice if the pop up error handled that and indicated the user should configure a new port.

![image (9)](https://user-images.githubusercontent.com/36768713/97572170-6ee64f00-19be-11eb-8613-088611603709.png)

**Comment by realkendrickren** [comment]
Thanks, @patbossman Agree. We will improve the message text for such case.

**Comment by realkendrickren** [comment]
@patbossman today we just released a new version 0.5.5 which addressed this one with a clearer message and a direct link to lead you to the page to customize the port. Please upgrade the extension in VSCode and give a try.
