### ISSUE TITLE
CREATE PROCEDURE deployment returns inaccurate error message

### ISSUE THREAD

**Issue by danluksetich** [IBM/db2forzosdeveloperextension-about#83]
When attempting to deploy a stored procedure on a Db2 12 M508 subsystem an error is returned. The specific error pertains to "USAGE OF" a user-defined array data type, which was needed for the stored procedure creation. This error is properly displayed when the stored procedure deployment is attempted using SPUFI or DSNTEP2. However, the error is returned in the developer extension as

DB2 SQL Error: SQLCODE=-551, SQLSTATE=42501, SQLERRMC=BNDDAN;CREATE;DANL.EMPNOS, DRIVER=4.29.24

The "CREATE" in this SQLERRMC should be "USAGE OF". This is likely an issue with JDBC as the same erroneous error message is returned in IBM Data Studio.

It would be amazingly easy for the IBM Db2 for z/OS Developer Extension developers to test this issue:
1) create a user-defined array data type.
CREATE TYPE DANL.EMPNOS AS CHAR(6) CCSID EBCDIC FOR SBCS DATA
ARRAY [500];
2) create a stored procedure that utilizes the data type but does not have the authority granted (USAGE OF) to the OWNER or the package owner.
CREATE PROCEDURE DANL.TESTPROC (IN P_EMPNOS DANL.EMPNOS)
OWNER PATB
PACKAGE OWNER PATB
P1:BEGIN
DECLARE MULT CURSOR WITH RETURN FOR
SELECT E.FIRSTNME
FROM  DSN81210.EMP E
INNER JOIN
UNNEST(P_EMPNOS) AS P(EMPNO)
ON E.EMPNO = P.EMPNO;
OPEN MULT;
END P1

the expected error would be
DB2 SQL Error: SQLCODE=-551, SQLSTATE=42501, SQLERRMC=PATB;USAGE OF;PNUMIZ.EMPNOS, DRIVER=4.29.24

the erroneous message is
DB2 SQL Error: SQLCODE=-551, SQLSTATE=42501, SQLERRMC=PATB;CREATE;PNUMIZ.EMPNOS, DRIVER=4.29.24

**Comment by katsoohoo** [comment]
Hi @danluksetich,

Thanks for reporting the issue. We will take a look on our side.

**Comment by katsoohoo** [comment]
Hi @danluksetich,

We could not recreate the issue on our side with JDBC driver version 4.29.24 (also tried 4.25.1301 and 4.31.10).

Here is the SQL we ran:
```
CREATE TYPE DANL.EMPNOS AS CHAR(6) CCSID EBCDIC FOR SBCS DATA ARRAY [500]#

CREATE PROCEDURE DANL.TESTPROC (IN P_EMPNOS DANL.EMPNOS)
PACKAGE OWNER PATB
P1:BEGIN
DECLARE MULT CURSOR WITH RETURN FOR
SELECT
  E.FIRSTNME
FROM
  DSN81210.EMP E
  INNER JOIN UNNEST(P_EMPNOS) AS P(EMPNO)
ON E.EMPNO = P.EMPNO;
OPEN MULT;
END P1#
```

The SQL error from the CREATE PROCEDURE statement produces the correct error message:
> DB2 SQL Error: SQLCODE=-551, SQLSTATE=42501, SQLERRMC=PATB;USAGE OF USER-DEFINED TYPE;DANL.EMPNOS, DRIVER=4.29.24

![Screen Shot 2022-06-06 at 11 13 17](https://user-images.githubusercontent.com/5027555/172220834-371433ae-ea94-4c4d-9db6-4919b1e01bce.png)

Could you also provide us with the [extension logs and JDBC logs](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs)?

**Comment by katsoohoo** [comment]
Hi @danluksetich,

Thanks for letting us know about your use of Top Secret. With this information, we'd like to do some more testing on our side. Let's hold off on the logs for now.

**Comment by danluksetich** [comment]
Yes, the user had the requisite privileges via Top Secret and could create the procedure without the array. When we figured out how to grant the authority to the array the error went away.

Dan

**Comment by katsoohoo** [comment]
Hi @danluksetich,

We went ahead and opened APAR PH47537 for this issue against Db2 for z/OS.

**Comment by danluksetich** [comment]
That is great! Thank you!

**Comment by katsoohoo** [comment]
Hi @danluksetich,

[APAR PH47537](https://www.ibm.com/support/pages/apar/PH47537) has been closed. Please let us know if your issue has been resolved.

**Comment by danluksetich** [comment]
Thanks! We do not have the PTF applied at this time but when we do I’ll test it.

Dan

**Comment by katsoohoo** [comment]
I will close this issue as the APAR fix has been provided.

**Comment by danluksetich** [comment]
Thank you, we still have not applied the fix so I have not been able to test it.

Dan

**Comment by katsoohoo** [comment]
No worries @danluksetich. If you find any issues after applying the fix, please let us know.
