### ISSUE TITLE
SQL Result view retains in dark mode even if VSCode is switched to a light color theme

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#84]
## Problem description

For some people the dark color theme is not perfect. VSCode has the possibility to swith into a light color theme but it's not possible to change the color theme of the Developer Extension SQL Results View.

**Comment by katsoohoo** [comment]
Hi @Marty850,

Thanks for reporting this. We will look into fixing this in the future.

**Comment by equalchenbj** [comment]
@Marty850 Light theme is delivered in v2.1.5. Refer to the [doc](https://ibm.github.io/db2forzosdeveloperextension-about/docs/tips-and-tricks/changing-the-color-theme.html) and have a try. Closing this issue. Feel free to reopen it if you have further questions.
