### ISSUE TITLE
I am connected but I get The query failed because it is not associated with a connection.

### ISSUE THREAD

**Issue by patbossman** [IBM/db2forzosdeveloperextension-about#9]
I have configured a connection to Db2 for z/OS.  I see "connected" next to the connection.

When I try to run the query I get pop up error "The query failed because it is not associated with a connection:
![image (10)](https://user-images.githubusercontent.com/36768713/97586158-53843f80-19d0-11eb-8642-d7fe8f57542a.png)

Then I notice on bottom left - "No Connection"
![image (11)](https://user-images.githubusercontent.com/36768713/97586313-7e6e9380-19d0-11eb-9c53-5a6d13c6026b.png)

I click on that, and choose my connection, then I see my connection and it works.
![Screen Shot 2020-10-29 at 10 07 32 AM](https://user-images.githubusercontent.com/36768713/97586432-a4943380-19d0-11eb-91fd-b9347887db08.png)

If I only have one connection, it would be nice if the files are automatically associated with that connection.

**Comment by realkendrickren** [comment]
Thanks. When there is only one connection profile defined in the extension, the connection is indeed associated automatically with the file when you try to run the SQLs in this version.

On the other hand, we are also planning to add more intelligence to improve the experience in connection association/management later. Stay tuned please.
