### ISSUE TITLE
Bad performance running a query with 19.000 rows in result

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#90]
## Development environment where the bug occurred

- Db2 Developer Extension version: 1.4.0
- Editor platform
  - [x] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version: 1.65.2
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7): Windows 10
- Java Version (Run `java -version` and paste the details here): 1.8.0_341
- Db2 for z/OS version (including function level for Db2 12): V12R1M510
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: No

## Problem description

We ran a query that had a result of 19.000 rows and noticed that it took very long in VS Code Developer Extension. It takes 4 minutes until you see the result. In Data Studio the same query shows the results after 8 seconds. The query is very fast in DB2. 

Maybe you can find something to optimize it.

**Comment by katsoohoo** [comment]
Hi @Marty850,

Thanks for reporting this performance issue. We will take a look.

**Comment by katsoohoo** [comment]
Hi @Marty850,

We've improved the performance for queries in v2.1.0. Please give it a try and let us know if the performance has improved.

**Comment by katsoohoo** [comment]
I will close this issue since the bug was fixed in v2.1.0.
