### ISSUE TITLE
Unable to connect to Tuning services 

### ISSUE THREAD

**Issue by mdasg2003** [IBM/db2forzosdeveloperextension-about#92]
We're unable to connect to Tuning Services to get the profiles. Seeing SSL errors in Tuning Services'  USS logs

**Comment by katsoohoo** [comment]
Hi @mdasg2003,

We created a temporary build based on v1.4 to better log the error message for your issue. Can you install the VSIX from the [issue92 branch](https://github.com/IBM/db2forzosdeveloperextension-about/tree/issue92) and check the logs when you hit this issue again?

**Comment by katsoohoo** [comment]
In v2.1.0, we've fixed the notification to display a proper error message.
