### ISSUE TITLE
Plan Table View in Visual Explain

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#94]
## Description of the feature or enhancement

We really like the visual explain functionality but in some cases it is helpful to have a look directly at the PLAN_TABLE. In DataStudio there is a button for "PLAN_TABLE view". It would be great to have that in VSCode Extension as well.

**Comment by katsoohoo** [comment]
Hi @Marty850,

Thank you for your suggestion. We will consider this.

**Comment by katsoohoo** [comment]
Hi @Marty850,

We will have this feature in the upcoming release.

**Comment by zhaoxq** [comment]
This is released in SQL Tuning service V2.0.

**Comment by zhaoxq** [comment]
Sorry to correct previous comments,  please install SQL Tuning Services 2.1.

**Comment by katsoohoo** [comment]
Closing this issue as the fix has been provided.
