### ISSUE TITLE
When using sslCertlocation JDBC parameter, username and password should not be marked mandatory

### ISSUE THREAD

**Issue by sowmyakam** [IBM/db2forzosdeveloperextension-about#99]
Many users use client auth where a local cert is generated using their user ID and password which is used for auth with Db2. The user ID and password are not needed in this case and right now user is expected to enter at least garbage values  to proceed with saving the connection. Whatever is entered here will not be used when sslCertLocation JDBC param is set.  
## Development environment where the bug occurred

- Db2 Developer Extension version: 2.1
- Editor platform
  - [ x ] Visual Studio Code
  - [ ] Eclipse Theia
- Editor platform version:
- Operating system on which your editor runs (for example, Windows 10 2004 or MacOS Catalina 10.15.7):
- Java Version (Run `java -version` and paste the details here):
- Db2 for z/OS version (including function level for Db2 12):
- [Log files](https://ibm.github.io/db2forzosdeveloperextension-about/docs/troubleshooting/opening-an-issue-and-providing-logs) attached?: Yes/No

## Problem description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior

-

### Expected behavior

-
<img width="1431" alt="Screen Shot 2023-03-30 at 7 07 34 AM" src="https://user-images.githubusercontent.com/36897706/229017104-fe1f9880-7846-4748-bbc8-8bdfcecd68c4.png">

**Comment by sowmyakam** [comment]
More context from Christoph Theisen (Solutions advisor)

sslCertLocation can be used for TLS server and client authentication and – in fact – we recommend this property to point their JDBC applications to a CA certificate.
 
Client authentication requires
sslConnection = true (of course)
sslCertLocation or equivalent for trusted CA certificates (e.g. Windows certificate store, JKS truststore)
securityMechanism=18  (or TLS_CLIENT_CERTIFICATE_SECURITY)
sslKeyStoreType / sslKeyStoreLocation / sslKeyStorePassword (depending on where the client certificate is located)
 
So users should have the option of “client certificate” in addition to Password, Passticket, MFA Token. Currently, Developer Extension is asking for a userid and password also in case of client certificate authentication. The password can just be any string, but it seems that Developer Extension sends the userid to the JDBC driver and – if it does not match the userid which is assigned to the certificate – some errors appear on the Db2 side (reason code 00D30051 “Required trusted context not defined in the Db2 for z/OS”). It might be the best, that, if the user selects that new option “Client Authentication” the userid and password are just greyed out and not sent to the JDBC driver.

**Comment by katsoohoo** [comment]
Thanks for reporting the issue @sowmyakam. We will take a look at this.

**Comment by katsoohoo** [comment]
Marking this as an enhancement since client certificate authentication is possible, but can be improved.

**Comment by BrianL674** [comment]
I agree this would be a useful enhancement.  And I assume easy to implement (but I should stop assuming things)

**Comment by sowmyakam** [comment]
@katsoohoo to add to the priority, we have couple more customers who have indicated they will use the extension only if it supports client certs to connect to db2 and although we have no issues connecting to Db2 with client certs, we do have this issue where we cannot connect without providing at least garbage values in the username and password field. i would vote for raising the priority on this one.

**Comment by equalchenbj** [comment]
Closing this issue as the feature is released in version v2.1.5.
